[package]
name = "pomd"
version = "1.3.0"
edition = "2021"

[dependencies]
notify-rust = "4"
zbus = "3.14.1"
async-std = { version = "1.12.0", features = ["attributes"] }
pausable_clock = "1.0.1"
confy = "0.5.1"
serde = "1.0.193"
